HMS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from hotel.api_views import RoomViewSet

router = routers.DefaultRouter()
router.register(r'rooms', RoomViewSet, basename='room')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('dr', include(router.urls)),
    path('', include('hotel.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/urls.py
from django.urls import path
from .views import BookingListView, RoomView, CancelBookingView, RoomCategoryListView, logout_user
from django.views.decorators.cache import cache_page

urlpatterns = [
    path('booking/list/', BookingListView.as_view(), name='bookings'),
    path('room/<str:category>', RoomView.as_view(), name='room'),
    path('booking/cancel/<str:pk>', CancelBookingView.as_view(), name='cancel'),
    path('', cache_page(60)(RoomCategoryListView.as_view()), name='rooms'),
    path('logout/', logout_user, name='logout'),
]

hotel/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse, reverse_lazy


class Room(models.Model):
    number = models.IntegerField(verbose_name='Room number')
    beds = models.IntegerField(verbose_name='The quatity of beds')
    capacity = models.IntegerField(verbose_name="The room's capacity")
    cat = models.ForeignKey('Category', on_delete=models.CASCADE, null=True, verbose_name='Category')

    def __str__(self):
        return f'[{self.number}] {self.cat} room with {self.beds} bed(s) for {self.capacity} people'


class Booking(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Guest')
    room = models.ForeignKey(Room, on_delete=models.CASCADE, verbose_name='Room')
    check_in = models.DateTimeField(verbose_name='Check in')
    check_out = models.DateTimeField(verbose_name='Check out')

    def __str__(self):
        return f'{self.user} has booked {self.room} from {self.check_in} to {self.check_out}'

    def get_cancel_booking_url(self):
        return reverse_lazy('cancel', kwargs={'pk': self.pk})


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name="The room's category")
    description = models.TextField(verbose_name='Description')
    slug = models.SlugField(max_length=50, unique=True, db_index=True, verbose_name='URL')
    image = models.ImageField(upload_to='hotel/category/', verbose_name="The room's photo")

    def __str__(self):
        return f'{self.name} room'

    def get_absolute_url(self):
        return reverse('room', kwargs={'category': self.slug})

hotel/forms.py
from django import forms
from .models import Room

class AvailabilityForm(forms.Form):
    check_in = forms.DateTimeField(required=True, input_formats=['%Y-%m-%d %H:%M', ])
    check_out = forms.DateTimeField(required=True, input_formats=['%Y-%m-%d %H:%M', ])

hotel/views.py
from django.contrib.auth import logout
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, View, DeleteView
from .models import Room, Booking, Category
from .forms import AvailabilityForm
from .booking_functions.availability import check_availability
from allauth.account.views import LoginView


class RoomCategoryListView(ListView):
    model = Category
    template_name = 'hotel/rooms.html'
    context_object_name = 'room_cats'


class BookingListView(ListView):
    """A list of bookings for the staff and clients"""
    template_name = "hotel/booking_list.html"
    context_object_name = 'bookings'

    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_staff:
            booking_list = Booking.objects.all().select_related('room')
            return booking_list
        else:
            booking_list = Booking.objects.filter(user=self.request.user).select_related('room')
            return booking_list


class RoomView(View):
    """Booking of a room"""

    def get(self, request, *args, **kwargs):
        category = self.kwargs.get('category', None)
        form = AvailabilityForm()
        room_list = Room.objects.filter(cat__slug=category)
        if len(room_list) > 0:
            room = room_list[0]
            context = {
                'room': room,
                'form': form,
            }
            return render(request, 'hotel/room.html', context)
        else:
            return HttpResponse('Sorry! This category does not exist!')

    def post(self, request, *args, **kwargs):
        category = self.kwargs.get('category', None)
        room_list = Room.objects.filter(cat__slug=category)
        form = AvailabilityForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data

        available_rooms = []
        for room in room_list:
            if check_availability(room, data['check_in'], data['check_out']):
                available_rooms.append(room)

        if len(available_rooms) > 0:
            room = available_rooms[0]
            booking = Booking.objects.create(
                user=self.request.user,
                room=room,
                check_in=data['check_in'],
                check_out=data['check_out']
            )
            booking.save()
            return HttpResponse(booking)
        else:
            return HttpResponse(
                'Sorry! All rooms of this kind of category is booked! Please, choose another room.')


class CancelBookingView(DeleteView):
    """Canceling of a booking"""
    model = Booking
    template_name = 'hotel/cancel_booking.html'
    success_url = reverse_lazy('bookings')
    context_object_name = 'booking'


def logout_user(request):
    logout(request)
    return redirect('rooms')

hotel/templates/hotel/booking_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking List</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'hotel/css/booking_list.css' %}">
</head>

<body>
    <div class="content">
        <div class="header">
            <div class="headings">
                <h1>Your Bookings</h1>
                <h2>Welcome dear {{user}}</h2>
            </div>
            <div class="home">
                <!-- Div 1: Back to Home -->
                <div class="home">
                    <a href="{% url 'rooms' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
                </div>
            </div>

        </div>

        <div class="bookings">
            {% for booking in bookings %}
            <div class="booking">
                <img src="{{booking.room.cat.image.url}}" alt="">
                <div class="category">
                    <h2>{{booking.room.cat.name}} Room</h2>
                </div>
                <div class="from">
                    <h3>From: {{booking.check_in}}</h3>
                </div>
                <div class="to">
                    <h3>To: {{booking.check_out}}</h3>
                </div>
                <div class="beds">
                    <h3>Beds: {{booking.room.beds}}</h3>
                </div>
                <div class="capacity">
                    <h3>Capacity: {{booking.room.capacity}}</h3>
                </div>
                <div class="cancel"><a href="{{booking.get_cancel_booking_url}}" class="invisible"><i
                            class="far fa-2x fa-times-circle"> Cancel
                            Booking</i></a></div>

            </div>
            {% endfor %}
        </div>
</body>

</html>

hotel/templates/hotel/cancel_booking.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Room Detail</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>

    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'hotel/css/detail.css' %}">

</head>

<body>


    <div class="content">
        <div class="image">
            <img
                src="{{booking.room.cat.image.url}}">
        </div>
        <div class="room">

            <div class="home">
                <a href="{% url 'rooms' %}"><i class="fas fa-arrow-alt-circle-left"> Home</i></a>
            </div>

            <div class="room-info">
                <h1>Canceling the room: {{booking.room.number}}</h1>
            </div>

            <!-- Div 3: Room Booking Form -->
            <form id="booking-form" action="" method="POST">

                {% csrf_token %}
                <h2>Dear {{booking.user}}</h2>
                <h2>Are you sure you wanna cancel this Booking?</h2>
                <div class="input-div">
                    <button type="submit">Cancel the Booking</button>
                </div>

            </form>

        </div>

    </div>

</body>

</html>

hotel/templates/hotel/room.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Room Detail</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'hotel/css/detail.css' %}">
</head>

<body>
<div class="content">
    <div class="image">
        <img
                src="{{room.cat.image.url}}">
    </div>
    <div class="room">
        <div class="home">
            <a href="{% url 'rooms' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
        </div>
        <div class="room-info">
            <h1 id="room-name">{{room.cat.name}}</h1>
            <p>{{room.cat.description}}</p>
        </div>
        <form id="booking-form" action="{% url 'bookings' %}" method="post">
            {% csrf_token %}
            <div class="input-div">
                <label for="id_check_in">Check In : </label>
                <input type="datetime-local" id="id_check_in" name="check_in">
            </div>
            <div class="input-div">
                <label for="id_check_out">Check Out : </label>
                <input type="datetime-local" id="id_check_out" name="check_out">
            </div>
            <div class="input-div">
                <button type="submit">Book the room </button>
            </div>
        </form>
    </div>
</div>
</body>

</html>

hotel/templates/hotel/room_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hotel-ST88</title>
    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'hotel/css/home.css' %}">
</head>

<body>
<!-- Brand -->
<h1 id="brand">Hotel Station-88</h1>

<!-- Main Content -->
<div class="content">
    {% for room_name, room_url in room_list %}
    <div class="room">
        <a href="{{room_url}}">
            <img
                    src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">

            <h2>{{room_name}}</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi</p>
        </a>
    </div>
    {% endfor %}
</div>
</body>
</html>

hotel/templates/hotel/rooms.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hotel-ST88</title>
    <link rel="stylesheet" href="{% static 'hotel/css/home.css'%}?20190811">
</head>
<body>
<ul class="mainmenu">
    <li><h1 class="brand">Hotel Station-88</h1></li>
    {% if request.user.is_authenticated %}
    <li><h1 class="brand"><a href="{% url 'bookings' %}">Booked rooms</a></h1></li>
    <li class="last"><h1 class="brand">{{user.username}}|<a href="{% url 'logout' %}">LogOut</a></h1></li>
    {% else %}
    <li class="last"><h1 class="brand"><a href="{% url 'account_signup' %}">SignUp</a> | <a href="{% url 'account_login' %}">LogIn</a></h1></li>
    {% endif %}
</ul>

<div class="content">
    {% for cat in room_cats %}
    <div class="room">
        <a href="{{cat.get_absolute_url}}">
            <img src="{{cat.image.url}}">
            <h2>{{cat.name}}</h2>
            <p>{{cat.description|linebreaks|truncatewords:20}}</p>
        </a>
    </div>
    {% endfor %}
</div>
</body>
</html>